version: '3'
services:
  keycloak-db:
    image: postgres:15
    restart: always
    container_name: keycloakv2_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@123
      POSTGRES_DB: keycloak_db
    volumes:
      - ./data:/var/lib/postgresql/data



